### ISSUE TITLE
different origin between robot and urdf

### ISSUE THREAD

**Issue by jih189** [CoppeliaRobotics/simExtURDF#3]
After I use the URDF import to import the urdf file, I found that the origin point of the mesh is different from the origin point of the object in the simulation. I found that is a really old issue like 3 years ago. Does anyone have fixed it?

**Comment by Coppelia** [comment]
Hello, this is normal in CoppeliaSim. The origin point of a mesh can be selected as one wishes, as long as the mesh keeps its pose. In CoppeliaSim a mesh's origin is always at the geom. center of the vertices. Orientation is usually selected as to have a bounding box with minimal sizes.

**Comment by jih189** [comment]
Because I am using ROS, and I want to publish the pose of the robot in simulation. Because the origin point of the robot mesh is not at the center and it is at the base, so the published pose will make the robot fly in the air. Is there anyway to publish the robot pose which is match with the mesh origin point?

**Comment by Coppelia** [comment]
Did you have a look at the simURDF.export function? It will export the meshes with the same origin as in CoppeliaSim, so they should match.
