### ISSUE TITLE
How to create a sim_message_eventcallback for URDF plugin?

### ISSUE THREAD

**Issue by GilmarCorreia** [CoppeliaRobotics/simExtURDF#4]
Hello CoppeliaSim Developers,

I'm a researcher working with the new CoppeliaSim version  (4.3.0 rev3), and I'm trying to develop a coppeliasim_ros2_control plugin to work and spawn controllers inside CoppeliaSim using ros2_control. The problem that I'm facing is requiring an understanding of the Coppelia Sim architecture.

How can I create a function inside Plugin.cpp that knows when simURDF.import() been called? For example:

onURDF_plugin(std::string urdf_contents)

If what I imagine is correct, I will need to create a sim_message_eventcallback_urdfplugin? How can I do it?

Thank you,

**Comment by Coppelia** [comment]
Hello Gilmar, please [contact us](https://www.coppeliarobotics.com/contact)

**Comment by GilmarCorreia** [comment]
Thank you! Problem solved!
